### ISSUE TITLE
Improve tests (meta ticket)

### ISSUE THREAD

**Issue by moul** [pathwar/portal.pathwar.net#18]
Ideas : 
- [x] Check other node.js versions
- [x] Test "gulp build"
- [x] Add node tests
- [x] Add browser tests

cc @cerisier @aimxhaisse

**Comment by moul** [comment]
Created dedicated issues for remaining tasks
