### ISSUE TITLE
[META TOPIC] School opening

### ISSUE THREAD

**Issue by moul** [pathwar/portal.pathwar.net#27]
There are specific needs for school opening, let's discuss everything here.

First, we need to only approve the (real) school students to access the session. Most of the students will create an account, but some of them will already have one and probably with their personal email address.
In most case we can ask the school for a list of email addresses to allow, and for the other school we can also fallback on a rule like `accept *@school-name.com`

---

Needs : 
- [ ] Allow the user to have multiple email addresses (and add the validation check per email address)
- [x] Allow the user to add custom field, for instance we can ask the student to put its student ID, so we can generate a CSV file with student ID and marks
- [ ] Give statistics to the teachers with our "appreciation", but give also enough detail so the teacher can create its custom notation rules (CSV with lots of data will be OK)
- [ ] Add on the admin portal a way to accept/refuse all the level validations and add details. Using multiple `five star` fields for pre-defined domains like "explanation", "originality", "skill" is cool to generate averages, sums and `tops skilled teams` etc
- [x] news
- [x] user info (`users`)
  - [x] create/join organizations (`organizations`, `organization-users`, `user-organization-invites`)
  - [ ] manage user tokens (`user-tokens`)
  - [x] see notifications (`user-notifications`)
- [x] organization info (`organisations`, `scoring`)
- [x] coupons
  - [x] a form to validate a new coupon
  - [ ] a listing of validated coupons
- ... (what is missing ?)
- [x] switch between organization (if > 1 organization joined)

Bonus sections : 
- [x] user activities / history
- [ ] shop
- [ ] achievements
- [ ] cool stats
  - [ ] coupon validations
  - [ ] level validation histogram etc
- [ ] public user profile
- [x] public organization profile

Bonus : 
- [ ] Give the teachers a teacher access to the portal so he can see deeper statistics
- [ ] Give the teachers some advices to help students

---

cc @cerisier @aimxhaisse @Solvik @blotus @vikbez @mlequeux

**Comment by aimxhaisse** [comment]
- t-shirt coupons (with regexp, ...)
- hidden coupons (we should not probably talk about this in public :D)
